### PR TITLE
use `player.avatar.src` to match convention used in other projects

### PR DESCRIPTION
**Pull request by shawnzam**
If `svgAvatar` is true get the `svg` property of the player.avatar as set in https://github.com/amaatouq/ge_task_bank. Happy and open to other suggestions, but this way we can just assign the avatar in server/main.js like

```javascript
import { avatarNames } from "../shared/avatars.js";
...
  const avatars = _.shuffle(avatarNames);

  game.players.forEach((player, i) => {
     player.set("avatar", avatars.pop());
   ...
```

### CODE REVIEW

**Comment by npaton** [comment]
I'm ok with making the avatar an object. I feel like it should have more than one field to justify the change. Maybe it's the opportunity to clean this up a bit. How about:

```js
{
  svg: "<svg>...",
  src: "http://...",
  alt: "a11y alt"
}
```

We can have `svg` have precedence over `src`. And we can remove `svgAvatar`.

We should make this change backward compatible. We can test whether the "avatar" key contains a string or an object and put out a deprecation warning.

We would need to update the documentation, but it would be pretty short, just an Avatar section in the Readme. Something like:

> You can set the Player's avatar with the "avatar" attribute on the Player object. The avatar attribute must be an object with either the `src` field (image URL "http://...") or the `svg` field (svg string "<svg>...") and optionally the `alt` text fields for accessiblity.
> For example:
> ```js
> player.set({
>    src: "http://example.com/example.jpeg",
>    alt: "An example image"
>  })
>  ```
> If both `src` and `svg` are given, `svg` takes precedence over `src`.

Does this make sense?

**Comment by shawnzam** [comment]
Makes perfect sense and will put it together shortly.

**Comment by shawnzam** [comment]
@npaton I made the changes we discussed. Kindly review and merge.

**Review by npaton — APPROVED** [review]
Looking good. Thank you!

**Comment by npaton** [comment]
@hubertusputu1 Can you release a new version when you get a chance. Thanks!

**Comment by hubertusputu1** [comment]
@npaton Noted, will do it soon.

**Comment by shawnzam** [comment]
@hubertusputu1 Just a gentle nudge to release a new version. Thanks!

**Comment by hubertusputu1** [comment]
@shawnzam My apologize for the delay 🙏🏻

**Comment by shawnzam** [comment]
Can you kindly check that you have released the latest build. It appears to be the wrong version. @hubertusputu1

**Comment by hubertusputu1** [comment]
@shawnzam Can you please check it once again? Thank you.

**Comment by shawnzam** [comment]
My bad, installed the package up a level than I intended.

**Pull request merged**
